Sun Feb 28 13:07:02 CST 2021
make[1]: Entering directory '/sources/Python-3.9.2'
LD_LIBRARY_PATH=/sources/Python-3.9.2 ./python -E -c 'import sys ; from sysconfig import get_platform ; print("%s-%d.%d" % (get_platform(), *sys.version_info[:2]))' >platform
LD_LIBRARY_PATH=/sources/Python-3.9.2 CC='gcc -pthread' LDSHARED='gcc -pthread -shared    ' OPT='-DNDEBUG -g -fwrapv -O3 -Wall' 	_TCLTK_INCLUDES='' _TCLTK_LIBS='' 	./python -E ./setup.py  build
running build
running build_ext
INFO: Can't locate Tcl/Tk libs and/or headers

Python build finished successfully!
The necessary bits to build these optional modules were not found:
_sqlite3              _tkinter              nis                
To find the necessary bits, look in setup.py in detect_modules() for the module's name.


The following modules found by detect_modules() in setup.py, have been
built by the Makefile instead, as configured by the Setup files:
_abc                  atexit                pwd                
time                                                           

running build_scripts
copying and adjusting /sources/Python-3.9.2/Tools/scripts/pydoc3 -> build/scripts-3.9
copying and adjusting /sources/Python-3.9.2/Tools/scripts/idle3 -> build/scripts-3.9
copying and adjusting /sources/Python-3.9.2/Tools/scripts/2to3 -> build/scripts-3.9
changing mode of build/scripts-3.9/pydoc3 from 664 to 775
changing mode of build/scripts-3.9/idle3 from 664 to 775
changing mode of build/scripts-3.9/2to3 from 664 to 775
renaming build/scripts-3.9/pydoc3 to build/scripts-3.9/pydoc3.9
renaming build/scripts-3.9/idle3 to build/scripts-3.9/idle3.9
renaming build/scripts-3.9/2to3 to build/scripts-3.9/2to3-3.9
LD_LIBRARY_PATH=/sources/Python-3.9.2 ./python  ./Tools/scripts/run_tests.py 
== CPython 3.9.2 (default, Feb 28 2021, 13:07:22) [GCC 10.2.0]
== Linux-5.10.17-lfs-10.1-rc1-x86_64-with-glibc2.33 little-endian
== cwd: /sources/Python-3.9.2/build/test_python_10110Ã¦
== CPU count: 24
== encodings: locale=UTF-8, FS=utf-8
Using random seed 7045667
0:00:00 load avg: 2.13 Run tests in parallel using 26 child processes
0:00:00 load avg: 2.13 [  1/425] test_tix skipped
test_tix skipped -- No module named '_tkinter'
0:00:00 load avg: 2.13 [  2/425] test_print passed
0:00:00 load avg: 2.13 [  3/425] test_bisect passed
0:00:00 load avg: 2.13 [  4/425] test_uu passed
0:00:00 load avg: 2.13 [  5/425] test_symtable passed
0:00:00 load avg: 2.13 [  6/425] test_pty passed
0:00:00 load avg: 2.13 [  7/425] test_global passed
0:00:00 load avg: 2.13 [  8/425] test_unpack passed
0:00:00 load avg: 2.13 [  9/425] test_grammar passed
0:00:00 load avg: 2.13 [ 10/425] test_call passed
0:00:00 load avg: 2.13 [ 11/425] test_file passed
0:00:00 load avg: 2.13 [ 12/425] test_univnewlines passed
0:00:00 load avg: 2.13 [ 13/425] test_repl passed
0:00:00 load avg: 2.13 [ 14/425] test_dataclasses passed
0:00:00 load avg: 2.13 [ 15/425] test_list passed
0:00:00 load avg: 2.13 [ 16/425] test_xdrlib passed
0:00:00 load avg: 2.13 [ 17/425] test_tcl skipped
test_tcl skipped -- No module named '_tkinter'
0:00:00 load avg: 2.13 [ 18/425] test_fileinput passed
0:00:00 load avg: 2.13 [ 19/425] test_defaultdict passed
0:00:00 load avg: 2.13 [ 20/425] test_imghdr passed
0:00:00 load avg: 2.13 [ 21/425] test_dbm_gnu passed
0:00:00 load avg: 2.13 [ 22/425] test_strptime passed
0:00:00 load avg: 2.13 [ 23/425] test_sysconfig passed
0:00:00 load avg: 2.13 [ 24/425] test_setcomps passed
0:00:00 load avg: 2.13 [ 25/425] test_genericclass passed
0:00:00 load avg: 2.13 [ 26/425] test_cgi passed
0:00:00 load avg: 2.13 [ 27/425] test_telnetlib passed
0:00:00 load avg: 2.13 [ 28/425] test_future passed
0:00:00 load avg: 2.13 [ 29/425] test_cprofile passed
0:00:00 load avg: 2.13 [ 30/425] test_dtrace passed
0:00:00 load avg: 2.13 [ 31/425] test_module passed
0:00:00 load avg: 2.13 [ 32/425] test_dict passed
0:00:00 load avg: 2.13 [ 33/425] test_finalization passed
0:00:00 load avg: 2.13 [ 34/425] test_future3 passed
0:00:01 load avg: 2.13 [ 35/425] test_code_module passed
0:00:01 load avg: 2.13 [ 36/425] test_doctest passed
0:00:01 load avg: 2.13 [ 37/425] test__osx_support passed
0:00:01 load avg: 2.13 [ 38/425] test_structmembers passed
0:00:01 load avg: 2.13 [ 39/425] test_operator passed
0:00:01 load avg: 2.13 [ 40/425] test_codecs passed
0:00:01 load avg: 2.13 [ 41/425] test_http_cookiejar passed
0:00:01 load avg: 2.13 [ 42/425] test_zipapp passed
0:00:01 load avg: 2.13 [ 43/425] test_genericpath passed
0:00:01 load avg: 2.13 [ 44/425] test_cmath passed
0:00:01 load avg: 2.13 [ 45/425] test_re passed
0:00:01 load avg: 2.13 [ 46/425] test_httplib passed
Resource 'self-signed.pythontest.net' is not available
Resource 'self-signed.pythontest.net' is not available
Resource 'self-signed.pythontest.net' is not available
Resource 'self-signed.pythontest.net' is not available
Resource 'www.python.org' is not available
0:00:01 load avg: 2.13 [ 47/425] test_thread passed
0:00:01 load avg: 2.13 [ 48/425] test_tuple passed
0:00:01 load avg: 2.13 [ 49/425] test_codecmaps_jp passed
0:00:01 load avg: 2.13 [ 50/425] test_bdb passed
0:00:01 load avg: 2.13 [ 51/425] test_future4 passed
0:00:01 load avg: 3.48 [ 52/425] test_sunau passed
0:00:01 load avg: 3.48 [ 53/425] test_py_compile passed
0:00:01 load avg: 3.48 [ 54/425] test_tracemalloc passed
0:00:01 load avg: 3.48 [ 55/425] test_userlist passed
0:00:01 load avg: 3.48 [ 56/425] test_inspect passed
0:00:01 load avg: 3.48 [ 57/425] test_generator_stop passed
0:00:01 load avg: 3.48 [ 58/425] test_platform passed
0:00:01 load avg: 3.48 [ 59/425] test_descr passed
0:00:01 load avg: 3.48 [ 60/425] test_dict_version passed
0:00:01 load avg: 3.48 [ 61/425] test_strftime passed
0:00:02 load avg: 3.48 [ 62/425] test_winsound skipped (resource denied)
test_winsound skipped -- Use of the 'audio' resource not enabled
0:00:02 load avg: 3.48 [ 63/425] test_xml_dom_minicompat passed
0:00:02 load avg: 3.48 [ 64/425] test_gc passed
0:00:02 load avg: 3.48 [ 65/425] test___all__ passed
0:00:02 load avg: 3.48 [ 66/425] test_xml_etree_c passed
0:00:02 load avg: 3.48 [ 67/425] test_unicode_identifiers passed
0:00:02 load avg: 3.48 [ 68/425] test_codeop passed
0:00:02 load avg: 3.48 [ 69/425] test_userstring passed
0:00:02 load avg: 3.48 [ 70/425] test_pstats passed
0:00:02 load avg: 3.48 [ 71/425] test_extcall passed
0:00:02 load avg: 3.48 [ 72/425] test_pyclbr passed
0:00:02 load avg: 3.48 [ 73/425] test_dynamic passed
0:00:02 load avg: 3.48 [ 74/425] test_codecencodings_kr passed
0:00:02 load avg: 3.48 [ 75/425] test_mimetypes passed
0:00:02 load avg: 3.48 [ 76/425] test_file_eintr passed
0:00:02 load avg: 3.48 [ 77/425] test_timeit passed
0:00:02 load avg: 3.48 [ 78/425] test_long passed
0:00:02 load avg: 3.48 [ 79/425] test_with passed
0:00:02 load avg: 3.48 [ 80/425] test_pdb passed
0:00:02 load avg: 3.48 [ 81/425] test_fnmatch passed
0:00:02 load avg: 3.48 [ 82/425] test_yield_from passed
0:00:02 load avg: 3.48 [ 83/425] test_ensurepip passed
0:00:02 load avg: 3.48 [ 84/425] test_ucn passed
0:00:02 load avg: 3.48 [ 85/425] test_unicode passed
0:00:02 load avg: 3.48 [ 86/425] test_random passed
0:00:03 load avg: 3.48 [ 87/425] test_fcntl passed
0:00:03 load avg: 3.48 [ 88/425] test_unpack_ex passed
0:00:03 load avg: 3.48 [ 89/425] test_zoneinfo passed
0:00:03 load avg: 3.48 [ 90/425] test_zipimport passed
0:00:03 load avg: 3.48 [ 91/425] test_getopt passed
0:00:03 load avg: 3.48 [ 92/425] test_memoryview passed
0:00:03 load avg: 3.48 [ 93/425] test_deque passed
0:00:03 load avg: 3.48 [ 94/425] test_tools passed
0:00:03 load avg: 3.48 [ 95/425] test_collections passed
0:00:03 load avg: 3.48 [ 96/425] test_dictcomps passed
0:00:03 load avg: 3.48 [ 97/425] test_dictviews passed
0:00:04 load avg: 3.48 [ 98/425] test_asyncgen passed
0:00:04 load avg: 3.48 [ 99/425] test_embed passed
0:00:04 load avg: 3.48 [100/425] test_startfile skipped
test_startfile skipped -- object <module 'os' from '/sources/Python-3.9.2/Lib/os.py'> has no attribute 'startfile'
0:00:04 load avg: 3.48 [101/425] test_urlparse passed
0:00:04 load avg: 3.48 [102/425] test_time passed
0:00:04 load avg: 3.48 [103/425] test_opcodes passed
0:00:04 load avg: 3.48 [104/425] test_wave passed
0:00:04 load avg: 3.48 [105/425] test_exception_hierarchy passed
0:00:04 load avg: 3.48 [106/425] test_robotparser passed
Resource 'http://www.pythontest.net/' is not available
0:00:04 load avg: 3.48 [107/425] test_wsgiref passed
0:00:04 load avg: 3.48 [108/425] test_bool passed
0:00:04 load avg: 3.48 [109/425] test_compile passed
0:00:04 load avg: 3.48 [110/425] test_sys_settrace passed
0:00:05 load avg: 3.48 [111/425] test_codecencodings_jp passed
0:00:05 load avg: 3.48 [112/425] test_threadsignals passed
0:00:05 load avg: 3.48 [113/425] test_frame passed
0:00:05 load avg: 3.48 [114/425] test_exceptions passed
0:00:05 load avg: 3.48 [115/425] test_slice passed
0:00:05 load avg: 3.48 [116/425] test_int_literal passed
0:00:05 load avg: 3.48 [117/425] test_dynamicclassattribute passed
0:00:05 load avg: 3.48 [118/425] test_named_expressions passed
0:00:05 load avg: 3.48 [119/425] test_pyexpat passed
0:00:05 load avg: 3.48 [120/425/1] test_curses failed
test test_curses failed -- Traceback (most recent call last):
  File "/sources/Python-3.9.2/Lib/test/test_curses.py", line 284, in test_output_string
    func(s)
_curses.error: inswstr() returned ERR
0:00:05 load avg: 3.48 [121/425/1] test_codecmaps_tw passed
0:00:06 load avg: 3.48 [122/425/1] test_multiprocessing_main_handling passed
0:00:06 load avg: 3.48 [123/425/1] test_largefile passed
0:00:06 load avg: 3.48 [124/425/1] test_rlcompleter passed
0:00:06 load avg: 3.48 [125/425/1] test_structseq passed
0:00:06 load avg: 3.48 [126/425/1] test_aifc passed
0:00:06 load avg: 4.32 [127/425/1] test_pathlib passed
0:00:06 load avg: 4.32 [128/425/1] test_email passed
0:00:07 load avg: 4.32 [129/425/1] test_eintr passed
0:00:07 load avg: 4.32 [130/425/1] test_userdict passed
0:00:07 load avg: 4.32 [131/425/1] test_clinic passed
0:00:07 load avg: 4.32 [132/425/1] test_keywordonlyarg passed
0:00:07 load avg: 4.32 [133/425/1] test_parser passed
0:00:07 load avg: 4.32 [134/425/1] test_enum passed
0:00:07 load avg: 4.32 [135/425/1] test_mmap passed
0:00:07 load avg: 4.32 [136/425/1] test_xmlrpc passed
0:00:07 load avg: 4.32 [137/425/1] test_builtin passed
0:00:07 load avg: 4.32 [138/425/1] test_tabnanny passed
0:00:07 load avg: 4.32 [139/425/1] test_sys_setprofile passed
0:00:07 load avg: 4.32 [140/425/1] test_cmd_line_script passed
0:00:07 load avg: 4.32 [141/425/1] test_abc passed
0:00:07 load avg: 4.32 [142/425/1] test_subclassinit passed
0:00:07 load avg: 4.32 [143/425/1] test_buffer passed
0:00:08 load avg: 4.32 [144/425/1] test_tk skipped
test_tk skipped -- No module named '_tkinter'
0:00:08 load avg: 4.32 [145/425/1] test_context passed
0:00:08 load avg: 4.32 [146/425/1] test_getpass passed
0:00:08 load avg: 4.32 [147/425/1] test_ossaudiodev skipped (resource denied)
test_ossaudiodev skipped -- Use of the 'audio' resource not enabled
0:00:08 load avg: 4.32 [148/425/1] test_codecencodings_cn passed
0:00:08 load avg: 4.32 [149/425/1] test_sys passed
0:00:08 load avg: 4.32 [150/425/1] test_fstring passed
0:00:08 load avg: 4.32 [151/425/1] test_wait3 passed
0:00:08 load avg: 4.32 [152/425/1] test_pipes passed
0:00:08 load avg: 4.32 [153/425/1] test_cmd passed
0:00:08 load avg: 4.32 [154/425/1] test_contextlib_async passed
Task was destroyed but it is pending!
task: <Task pending name='Task-9' coro=<<async_generator_athrow without __name__>()>>
Task was destroyed but it is pending!
task: <Task pending name='Task-11' coro=<<async_generator_athrow without __name__>()>>
Task was destroyed but it is pending!
task: <Task pending name='Task-16' coro=<<async_generator_athrow without __name__>()>>
0:00:08 load avg: 4.32 [155/425/1] test_osx_env passed
0:00:08 load avg: 4.32 [156/425/1] test_generators passed
0:00:08 load avg: 4.32 [157/425/1] test_funcattrs passed
0:00:08 load avg: 4.32 [158/425/1] test_urllib_response passed
0:00:08 load avg: 4.32 [159/425/1] test_pprint passed
0:00:08 load avg: 4.32 [160/425/1] test_bigmem passed
0:00:08 load avg: 4.32 [161/425/1] test_codecmaps_cn passed
0:00:08 load avg: 4.32 [162/425/1] test_spwd passed
0:00:08 load avg: 4.32 [163/425/1] test_c_locale_coercion passed
0:00:09 load avg: 4.32 [164/425/1] test_tempfile passed
0:00:09 load avg: 4.32 [165/425/1] test_unicode_file_functions passed
0:00:09 load avg: 4.32 [166/425/1] test_index passed
0:00:09 load avg: 4.32 [167/425/1] test_itertools passed
0:00:09 load avg: 4.32 [168/425/1] test_decorators passed
0:00:09 load avg: 4.32 [169/425/1] test_property passed
0:00:09 load avg: 4.32 [170/425/1] test_posix passed
0:00:09 load avg: 4.32 [171/425/1] test_site passed
Resource 'https://www.python.org/psf/license/' is not available
0:00:09 load avg: 4.32 [172/425/1] test_glob passed
0:00:09 load avg: 4.32 [173/425/1] test_turtle skipped
test_turtle skipped -- No module named '_tkinter'
0:00:09 load avg: 4.32 [174/425/1] test_smtplib passed
0:00:09 load avg: 4.32 [175/425/1] test_baseexception passed
0:00:09 load avg: 4.32 [176/425/1] test_source_encoding passed
0:00:09 load avg: 4.32 [177/425/1] test_netrc passed
0:00:09 load avg: 4.32 [178/425/1] test_fork1 passed
0:00:09 load avg: 4.32 [179/425/1] test_getargs2 passed
0:00:09 load avg: 4.32 [180/425/1] test_check_c_globals passed
0:00:09 load avg: 4.32 [181/425/1] test_ftplib passed
0:00:09 load avg: 4.32 [182/425/1] test_ntpath passed
0:00:10 load avg: 4.32 [183/425/1] test_codecmaps_hk passed
0:00:10 load avg: 4.32 [184/425/1] test_zipfile passed
0:00:10 load avg: 4.32 [185/425/1] test_zipimport_support passed
0:00:10 load avg: 4.32 [186/425/1] test__xxsubinterpreters passed
0:00:10 load avg: 4.32 [187/425/1] test_popen passed
0:00:10 load avg: 4.32 [188/425/1] test_mailcap passed
0:00:10 load avg: 4.32 [189/425/1] test_reprlib passed
0:00:10 load avg: 4.32 [190/425/1] test_lltrace passed
0:00:10 load avg: 4.32 [191/425/1] test_fractions passed
0:00:10 load avg: 4.32 [192/425/1] test_secrets passed
0:00:10 load avg: 4.32 [193/425/1] test_support passed
0:00:11 load avg: 4.32 [194/425/1] test_trace passed
0:00:11 load avg: 4.32 [195/425/1] test_httpservers passed
0:00:11 load avg: 5.02 [196/425/1] test_hashlib passed
0:00:11 load avg: 5.02 [197/425/1] test_binop passed
0:00:11 load avg: 5.02 [198/425/1] test_configparser passed
0:00:11 load avg: 5.02 [199/425/1] test_ast passed
0:00:11 load avg: 5.02 [200/425/1] test_timeout passed
Resource 'www.python.org.' is not available
Resource 'www.python.org.' is not available
Resource 'www.python.org.' is not available
Resource 'www.python.org.' is not available
Resource 'www.python.org.' is not available
/sources/Python-3.9.2/Lib/test/support/__init__.py:1438: ResourceWarning: unclosed <socket.socket fd=4, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('0.0.0.0', 0)>
  gc.collect()
ResourceWarning: Enable tracemalloc to get the object allocation traceback
/sources/Python-3.9.2/Lib/test/support/__init__.py:1438: ResourceWarning: unclosed <socket.socket fd=5, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('0.0.0.0', 0)>
  gc.collect()
ResourceWarning: Enable tracemalloc to get the object allocation traceback
/sources/Python-3.9.2/Lib/test/support/__init__.py:1438: ResourceWarning: unclosed <socket.socket fd=6, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('0.0.0.0', 0)>
  gc.collect()
ResourceWarning: Enable tracemalloc to get the object allocation traceback
/sources/Python-3.9.2/Lib/test/support/__init__.py:1438: ResourceWarning: unclosed <socket.socket fd=7, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('0.0.0.0', 0)>
  gc.collect()
ResourceWarning: Enable tracemalloc to get the object allocation traceback
/sources/Python-3.9.2/Lib/test/support/__init__.py:1438: ResourceWarning: unclosed <socket.socket fd=3, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('0.0.0.0', 0)>
  gc.collect()
ResourceWarning: Enable tracemalloc to get the object allocation traceback
0:00:11 load avg: 5.02 [201/425/1] test_exception_variations passed
0:00:12 load avg: 5.02 [202/425/1] test_float passed
0:00:12 load avg: 5.02 [203/425/1] test_hash passed
0:00:12 load avg: 5.02 [204/425/1] test_bz2 passed
0:00:12 load avg: 5.02 [205/425/1] test_readline passed
0:00:12 load avg: 5.02 [206/425/1] test_imp passed
0:00:12 load avg: 5.02 [207/425/1] test_pickle passed
0:00:12 load avg: 5.02 [208/425/1] test_utf8_mode passed
0:00:12 load avg: 5.02 [209/425/1] test_filecmp passed
0:00:12 load avg: 5.02 [210/425/1] test_typechecks passed
0:00:12 load avg: 5.02 [211/425/1] test_enumerate passed
0:00:12 load avg: 5.02 [212/425/1] test_codecmaps_kr passed
0:00:12 load avg: 5.02 [213/425/1] test_future5 passed
0:00:13 load avg: 5.02 [214/425/1] test_frozen passed
0:00:13 load avg: 5.02 [215/425/1] test_distutils passed
0:00:13 load avg: 5.02 [216/425/1] test_positional_only_arg passed
0:00:13 load avg: 5.02 [217/425/1] test_urllib2_localnet passed
0:00:13 load avg: 5.02 [218/425/1] test_difflib passed
0:00:13 load avg: 5.02 [219/425/1] test_descrtut passed
0:00:13 load avg: 5.02 [220/425/1] test_ipaddress passed
0:00:13 load avg: 5.02 [221/425/1] test_threading passed
0:00:13 load avg: 5.02 [222/425/1] test_optparse passed
0:00:13 load avg: 5.02 [223/425/1] test_msilib skipped
test_msilib skipped -- No module named '_msi'
0:00:13 load avg: 5.02 [224/425/1] test_code passed
0:00:13 load avg: 5.02 [225/425/1] test_socketserver passed
0:00:13 load avg: 5.02 [226/425/1] test_textwrap passed
0:00:13 load avg: 5.02 [227/425/1] test_sundry passed
0:00:13 load avg: 5.02 [228/425/1] test_type_comments passed
0:00:14 load avg: 5.02 [229/425/1] test_idle skipped
test_idle skipped -- No module named '_tkinter'
0:00:14 load avg: 5.02 [230/425/1] test_base64 passed
0:00:14 load avg: 5.02 [231/425/1] test___future__ passed
0:00:14 load avg: 5.02 [232/425/1] test_poplib passed
0:00:14 load avg: 5.02 [233/425/1] test_traceback passed
0:00:14 load avg: 5.02 [234/425/1] test_stringprep passed
0:00:14 load avg: 5.02 [235/425/1] test_shelve passed
0:00:14 load avg: 5.02 [236/425/1] test_stat passed
0:00:14 load avg: 5.02 [237/425/1] test_smtpd passed
0:00:14 load avg: 5.02 [238/425/1] test_threading_local passed
0:00:14 load avg: 5.02 [239/425/1] test_dbm_dumb passed
0:00:14 load avg: 5.02 [240/425/1] test_range passed
0:00:14 load avg: 5.02 [241/425/1] test_openpty passed
0:00:14 load avg: 5.02 [242/425/1] test_statistics passed
0:00:14 load avg: 5.02 [243/425/1] test_modulefinder passed
0:00:14 load avg: 5.02 [244/425/1] test_sqlite skipped
test_sqlite skipped -- No module named '_sqlite3'
0:00:14 load avg: 5.02 [245/425/2] test_unicodedata failed
test test_unicodedata failed -- Traceback (most recent call last):
  File "/sources/Python-3.9.2/Lib/urllib/request.py", line 1346, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
socket.gaierror: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/sources/Python-3.9.2/Lib/test/test_unicodedata.py", line 329, in test_normalization
    testdata = open_urlresource(TESTDATAURL, encoding="utf-8",
urllib.error.URLError: <urlopen error [Errno -3] Temporary failure in name resolution>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/sources/Python-3.9.2/Lib/test/test_unicodedata.py", line 335, in test_normalization
    self.fail(f"Could not retrieve {TESTDATAURL}")
AssertionError: Could not retrieve http://www.pythontest.net/unicode/13.0.0/NormalizationTest.txt
0:00:14 load avg: 5.02 [246/425/2] test_unary passed
0:00:14 load avg: 5.02 [247/425/2] test_resource passed
0:00:14 load avg: 5.02 [248/425/2] test_hmac passed
0:00:15 load avg: 5.02 [249/425/2] test_copy passed
0:00:15 load avg: 5.02 [250/425/2] test_ttk_textonly skipped
test_ttk_textonly skipped -- No module named '_tkinter'
0:00:15 load avg: 5.02 [251/425/2] test_htmlparser passed
0:00:15 load avg: 5.02 [252/425/2] test_urllib2net passed
Resource 'http://www.pythontest.net' is not available
Resource 'http://www.pythontest.net' is not available
Resource 'ftp://www.pythontest.net/README' is not available
Resource 'http://www.pythontest.net/redir/with_frag/' is not available
Resource 'http://www.pythontest.net/index.html#frag' is not available
Resource 'ftp://www.pythontest.net/' is not available
Resource 'ftp://www.pythontest.net/' is not available
Resource 'ftp://www.pythontest.net/' is not available
Resource 'ftp://www.pythontest.net/' is not available
Resource 'http://www.pythontest.net' is not available
Resource 'http://www.pythontest.net' is not available
Resource 'http://www.pythontest.net' is not available
Resource 'http://www.pythontest.net' is not available
0:00:15 load avg: 5.02 [253/425/2] test_contextlib passed
0:00:15 load avg: 5.02 [254/425/2] test_regrtest passed
0:00:15 load avg: 5.02 [255/425/2] test__locale passed
0:00:15 load avg: 5.02 [256/425/2] test_posixpath passed
0:00:15 load avg: 5.02 [257/425/2] test_codeccallbacks passed
0:00:15 load avg: 5.02 [258/425/2] test_wait4 passed
0:00:15 load avg: 5.02 [259/425/2] test_calendar passed
0:00:15 load avg: 5.02 [260/425/2] test_pwd passed
0:00:15 load avg: 5.02 [261/425/2] test_class passed
0:00:15 load avg: 5.02 [262/425/2] test_script_helper passed
0:00:15 load avg: 5.02 [263/425/2] test_threadedtempfile passed
0:00:15 load avg: 5.02 [264/425/2] test_functools passed
0:00:16 load avg: 5.02 [265/425/2] test_augassign passed
0:00:16 load avg: 5.02 [266/425/2] test_iterlen passed
0:00:16 load avg: 5.02 [267/425/2] test_uuid passed
0:00:16 load avg: 5.02 [268/425/2] test_pickletools passed
0:00:16 load avg: 5.02 [269/425/2] test_winconsoleio skipped
test_winconsoleio skipped -- test only relevant on win32
0:00:16 load avg: 5.02 [270/425/2] test_zipfile64 skipped (resource denied)
test_zipfile64 skipped -- test requires loads of disk-space bytes and a long time to run
0:00:16 load avg: 5.02 [271/425/2] test_asynchat passed
0:00:16 load avg: 5.02 [272/425/2] test_smtpnet passed
Resource 'smtp.gmail.com' is not available
Resource 'smtp.gmail.com' is not available
Resource 'smtp.gmail.com' is not available
Resource 'smtp.gmail.com' is not available
Resource 'smtp.gmail.com' is not available
0:00:16 load avg: 5.02 [273/425/2] test_ssl passed
/sources/Python-3.9.2/Lib/test/support/__init__.py:3105: ResourceWarning: unclosed <ssl.SSLSocket fd=5, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 48977), raddr=('127.0.0.1', 50098)>
  del self.thread
ResourceWarning: Enable tracemalloc to get the object allocation traceback
Resource 'ipv6.google.com' is not available
Resource 'self-signed.pythontest.net' is not available
0:00:16 load avg: 5.74 [274/425/2] test_ctypes passed
0:00:16 load avg: 5.74 [275/425/2] test_gzip passed
0:00:16 load avg: 5.74 [276/425/2] test_codecencodings_tw passed
0:00:16 load avg: 5.74 [277/425/2] test_ioctl skipped
test_ioctl skipped -- Unable to open /dev/tty
0:00:16 load avg: 5.74 [278/425/2] test_string passed
0:00:16 load avg: 5.74 [279/425/2] test_shutil passed
0:00:17 load avg: 5.74 [280/425/2] test_super passed
0:00:17 load avg: 5.74 [281/425/2] test_lzma passed
0:00:17 load avg: 5.74 [282/425/2] test_argparse passed
0:00:17 load avg: 5.74 [283/425/2] test_minidom passed
0:00:17 load avg: 5.74 [284/425/2] test_ordered_dict passed
0:00:17 load avg: 5.74 [285/425/2] test_locale passed
0:00:17 load avg: 5.74 [286/425/2] test_kqueue skipped
test_kqueue skipped -- test works only on BSD
0:00:17 load avg: 5.74 [287/425/2] test_memoryio passed
0:00:18 load avg: 5.74 [288/425/2] test_runpy passed
0:00:18 load avg: 5.74 [289/425/2] test_set passed
0:00:18 load avg: 5.74 [290/425/2] test_crypt passed
0:00:18 load avg: 5.74 [291/425/2] test_dbm passed
0:00:18 load avg: 5.74 [292/425/2] test_iter passed
0:00:18 load avg: 5.74 [293/425/2] test_importlib passed
0:00:18 load avg: 5.74 [294/425/2] test_xml_etree passed
0:00:18 load avg: 5.74 [295/425/2] test_venv passed
0:00:18 load avg: 5.74 [296/425/2] test_atexit passed
0:00:19 load avg: 5.74 [297/425/2] test_audit passed
0:00:19 load avg: 5.74 [298/425/2] test_crashers passed
0:00:19 load avg: 5.74 [299/425/2] test_gettext passed
0:00:19 load avg: 5.74 [300/425/2] test_types passed
0:00:19 load avg: 5.74 [301/425/2] test_string_literals passed
0:00:19 load avg: 5.74 [302/425/2] test_nis skipped
test_nis skipped -- No module named 'nis'
0:00:19 load avg: 5.74 [303/425/2] test_profile passed
0:00:19 load avg: 5.74 [304/425/2] test_bufio passed
0:00:19 load avg: 5.74 [305/425/2] test_colorsys passed
0:00:19 load avg: 5.74 [306/425/2] test_metaclass passed
0:00:19 load avg: 5.74 [307/425/2] test_codecencodings_hk passed
0:00:19 load avg: 5.74 [308/425/2] test_bigaddrspace passed
0:00:19 load avg: 5.74 [309/425/2] test_devpoll skipped
test_devpoll skipped -- test works only on Solaris OS family
0:00:19 load avg: 5.74 [310/425/2] test_numeric_tower passed
0:00:19 load avg: 5.74 [311/425/2] test_pkgutil passed
0:00:19 load avg: 5.74 [312/425/2] test_quopri passed
0:00:20 load avg: 5.74 [313/425/2] test_xmlrpc_net passed
0:00:20 load avg: 5.74 [314/425/2] test_weakset passed
0:00:20 load avg: 5.74 [315/425/2] test_pulldom passed
0:00:20 load avg: 5.74 [316/425/2] test_grp passed
0:00:21 load avg: 5.74 [317/425/2] test_poll passed
0:00:21 load avg: 5.74 [318/425/2] test_faulthandler passed
0:00:21 load avg: 5.74 [319/425/2] test_syntax passed
0:00:21 load avg: 5.74 [320/425/2] test_gdb skipped
test_gdb skipped -- Couldn't find gdb on the path
0:00:21 load avg: 5.74 [321/425/2] test_raise passed
0:00:21 load avg: 5.74 [322/425/2] test_plistlib passed
0:00:21 load avg: 5.74 [323/425/2] test_cmd_line passed
0:00:21 load avg: 5.74 [324/425/2] test_tarfile passed
0:00:21 load avg: 5.74 [325/425/2] test_codecencodings_iso2022 passed
0:00:21 load avg: 5.74 [326/425/2] test_fileio passed
0:00:21 load avg: 5.74 [327/425/2] test_genericalias passed
0:00:21 load avg: 6.32 [328/425/2] test_nntplib passed
Resource 'news.trigofacile.com' is not available
Resource 'nntp.aioe.org' is not available
0:00:21 load avg: 6.32 [329/425/2] test_charmapcodec passed
0:00:21 load avg: 6.32 [330/425/2] test__opcode passed
0:00:21 load avg: 6.32 [331/425/2] test_logging passed
0:00:21 load avg: 6.32 [332/425/2] test_genexps passed
0:00:21 load avg: 6.32 [333/425/2] test_sndhdr passed
0:00:21 load avg: 6.32 [334/425/2] test_capi passed
0:00:21 load avg: 6.32 [335/425/2] test_urllib passed
0:00:21 load avg: 6.32 [336/425/2] test_eof passed
0:00:22 load avg: 6.32 [337/425/2] test_dbm_ndbm passed
0:00:22 load avg: 6.32 [338/425/2] test_pow passed
0:00:22 load avg: 6.32 [339/425/2] test_heapq passed
0:00:22 load avg: 6.32 [340/425/2] test_winreg skipped
test_winreg skipped -- No module named 'winreg'
0:00:22 load avg: 6.32 [341/425/2] test_compileall passed
0:00:22 load avg: 6.32 [342/425/2] test_array passed
0:00:22 load avg: 6.32 [343/425/2] test_warnings passed
0:00:22 load avg: 6.32 [344/425/2] test_isinstance passed
0:00:22 load avg: 6.32 [345/425/2] test_strtod passed
0:00:22 load avg: 6.32 [346/425/2] test_graphlib passed
0:00:22 load avg: 6.32 [347/425/2] test_utf8source passed
0:00:22 load avg: 6.32 [348/425/2] test_webbrowser passed
0:00:22 load avg: 6.32 [349/425/2] test_pkg passed
0:00:22 load avg: 6.32 [350/425/2] test_syslog passed
0:00:22 load avg: 6.32 [351/425/2] test_bytes passed
0:00:23 load avg: 6.32 [352/425/2] test_longexp passed
0:00:23 load avg: 6.32 [353/425/2] test_flufl passed
0:00:23 load avg: 6.32 [354/425/2] test_coroutines passed
0:00:23 load avg: 6.32 [355/425/2] test_errno passed
0:00:23 load avg: 6.32 [356/425/2] test_socket passed
Resource 'python.org' is not available
0:00:23 load avg: 6.32 [357/425/2] test_sort passed
0:00:23 load avg: 6.32 [358/425/2] test_decimal passed
0:00:23 load avg: 6.32 [359/425/2] test_int passed
0:00:23 load avg: 6.32 [360/425/2] test_dis passed
0:00:23 load avg: 6.32 [361/425/2] test_complex passed
0:00:23 load avg: 6.32 [362/425/2] test_docxmlrpc passed
0:00:23 load avg: 6.32 [363/425/2] test_sched passed
0:00:23 load avg: 6.32 [364/425/2] test_urllibnet passed
Resource 'www.pythontest.net' is not available
Resource 'http://www.pythontest.net/' is not available
Resource 'http://www.pythontest.net/XXXinvalidXXX' is not available
Resource 'http://www.pythontest.net/' is not available
Resource 'http://www.pythontest.net/' is not available
Resource 'http://www.pythontest.net/' is not available
Resource 'http://www.pythontest.net/' is not available
Resource 'http://www.pythontest.net/' is not available
Resource 'http://www.pythontest.net/' is not available
Resource 'http://www.pythontest.net/' is not available
Resource 'http://www.pythontest.net/' is not available
0:00:23 load avg: 6.32 [365/425/2] test_linecache passed
0:00:23 load avg: 6.32 [366/425/2] test_doctest2 passed
0:00:23 load avg: 6.32 [367/425/2] test_compare passed
0:00:23 load avg: 6.32 [368/425/2] test_csv passed
0:00:23 load avg: 6.32 [369/425/2] test_unicode_file passed
0:00:23 load avg: 6.32 [370/425/2] test_contains passed
0:00:23 load avg: 6.32 [371/425/2] test_typing passed
/sources/Python-3.9.2/Lib/_collections_abc.py:433: DeprecationWarning: Callable must be used as Callable[[arg, ...], result]. (This will raise a TypeError in Python 3.10.)
  warnings.warn(f'{str(exc)} '
0:00:23 load avg: 6.32 [372/425/2] test_format passed
0:00:23 load avg: 6.32 [373/425/2] test_http_cookies passed
0:00:23 load avg: 6.32 [374/425/2] test_datetime passed
0:00:23 load avg: 6.32 [375/425/2] test_asdl_parser passed
0:00:23 load avg: 6.32 [376/425/2] test_audioop passed
0:00:23 load avg: 6.32 [377/425/2] test_sax passed
0:00:23 load avg: 6.32 [378/425/2] test_selectors passed
0:00:23 load avg: 6.32 [379/425/2] test_cgitb passed
0:00:24 load avg: 6.32 [380/425/2] test_urllib2 passed
Resource 'http://www.example.com/' is not available
0:00:24 load avg: 6.32 [381/425/2] test_html passed
0:00:24 load avg: 6.32 [382/425/2] test_symbol passed
0:00:24 load avg: 6.32 [383/425/2] test_shlex passed
0:00:24 load avg: 6.32 [384/425/2] test_ttk_guionly skipped
test_ttk_guionly skipped -- No module named '_tkinter'
0:00:24 load avg: 6.32 [385/425/2] test_binascii passed
0:00:24 load avg: 6.32 [386/425/2] test_struct passed
0:00:24 load avg: 6.32 [387/425/2] test_epoll passed
0:00:24 load avg: 6.32 [388/425/2] test_peg_parser passed
0:00:24 load avg: 6.32 [389/425/2] test_binhex passed
0:00:24 load avg: 6.32 [390/425/2] test_marshal passed
0:00:24 load avg: 6.32 [391/425/2] test_mailbox passed
0:00:24 load avg: 6.32 [392/425/2] test_abstract_numbers passed
0:00:24 load avg: 6.32 [393/425/2] test_richcmp passed
0:00:24 load avg: 6.32 [394/425/2] test_xxtestfuzz passed
0:00:24 load avg: 6.32 [395/425/2] test_os passed
0:00:24 load avg: 6.32 [396/425/2] test_weakref passed
0:00:24 load avg: 6.32 [397/425/2] test_copyreg passed
0:00:24 load avg: 6.32 [398/425/2] test_keyword passed
0:00:24 load avg: 6.32 [399/425/2] test_peepholer passed
0:00:24 load avg: 6.32 [400/425/2] test_zlib passed
0:00:24 load avg: 6.32 [401/425/2] test_listcomps passed
0:00:24 load avg: 6.32 [402/425/2] test_picklebuffer passed
0:00:25 load avg: 6.32 [403/425/2] test_scope passed
0:00:25 load avg: 6.32 [404/425/2] test_import passed
0:00:25 load avg: 6.32 [405/425/2] test_multibytecodec passed
0:00:25 load avg: 6.32 [406/425/2] test_asyncore passed
0:00:26 load avg: 6.32 [407/425/2] test_lib2to3 passed
0:00:26 load avg: 6.32 [408/425/2] test_unittest passed
0:00:26 load avg: 6.32 [409/425/2] test_math passed
0:00:26 load avg: 6.32 [410/425/2] test_json passed
0:00:27 load avg: 6.13 [411/425/2] test_queue passed
0:00:32 load avg: 6.04 [412/425/2] test_tokenize passed (31.2 sec) -- running: test_multiprocessing_forkserver (32.0 sec), test_io (30.6 sec), test_concurrent_futures (31.3 sec)
0:00:34 load avg: 6.04 [413/425/2] test_select passed -- running: test_asyncio (32.4 sec), test_multiprocessing_spawn (30.2 sec), test_multiprocessing_forkserver (34.6 sec), test_io (33.2 sec), test_peg_generator (32.3 sec), test_concurrent_futures (33.9 sec)
0:00:37 load avg: 5.88 [414/425/2] test_imaplib passed -- running: test_asyncio (35.0 sec), test_multiprocessing_spawn (32.9 sec), test_multiprocessing_forkserver (37.2 sec), test_io (35.8 sec), test_peg_generator (34.9 sec), test_concurrent_futures (36.5 sec)
0:00:37 load avg: 5.88 [415/425/2] test_io passed (35.9 sec) -- running: test_asyncio (35.2 sec), test_multiprocessing_spawn (33.1 sec), test_multiprocessing_forkserver (37.4 sec), test_peg_generator (35.1 sec), test_concurrent_futures (36.7 sec)
0:00:40 load avg: 5.88 [416/425/2] test_subprocess passed -- running: test_asyncio (38.5 sec), test_multiprocessing_fork (31.4 sec), test_multiprocessing_spawn (36.3 sec), test_multiprocessing_forkserver (40.7 sec), test_peg_generator (38.4 sec), test_concurrent_futures (40.0 sec)
/sources/Python-3.9.2/Lib/subprocess.py:1052: ResourceWarning: subprocess 16871 is still running
  _warn("subprocess %s is still running" % self.pid,
ResourceWarning: Enable tracemalloc to get the object allocation traceback
0:00:40 load avg: 5.88 [417/425/2] test_unparse passed -- running: test_asyncio (38.5 sec), test_multiprocessing_fork (31.4 sec), test_multiprocessing_spawn (36.4 sec), test_multiprocessing_forkserver (40.7 sec), test_peg_generator (38.4 sec), test_concurrent_futures (40.0 sec)
0:00:51 load avg: 5.10 [418/425/2] test_asyncio passed (49.4 sec) -- running: test_multiprocessing_fork (42.4 sec), test_multiprocessing_spawn (47.4 sec), test_multiprocessing_forkserver (51.7 sec), test_signal (36.5 sec), test_peg_generator (49.4 sec), test_concurrent_futures (51.0 sec)
0:00:53 load avg: 5.10 [419/425/2] test_pydoc passed (31.1 sec) -- running: test_multiprocessing_fork (43.8 sec), test_multiprocessing_spawn (48.8 sec), test_multiprocessing_forkserver (53.1 sec), test_signal (37.9 sec), test_peg_generator (50.8 sec), test_concurrent_futures (52.4 sec)
0:01:00 load avg: 4.78 [420/425/2] test_multiprocessing_fork passed (50.9 sec) -- running: test_multiprocessing_spawn (56.0 sec), test_multiprocessing_forkserver (1 min), test_signal (45.2 sec), test_peg_generator (58.1 sec), test_concurrent_futures (59.7 sec)
0:01:00 load avg: 4.78 [421/425/2] test_multiprocessing_forkserver passed (1 min) -- running: test_multiprocessing_spawn (56.2 sec), test_signal (45.4 sec), test_peg_generator (58.3 sec), test_concurrent_futures (59.9 sec)
0:01:01 load avg: 4.47 [422/425/2] test_signal passed (46.6 sec) -- running: test_multiprocessing_spawn (57.5 sec), test_peg_generator (59.6 sec), test_concurrent_futures (1 min 1 sec)
0:01:06 load avg: 4.47 [423/425/2] test_multiprocessing_spawn passed (1 min 1 sec) -- running: test_peg_generator (1 min 4 sec), test_concurrent_futures (1 min 5 sec)
0:01:31 load avg: 3.10 [424/425/2] test_peg_generator passed (1 min 29 sec) -- running: test_concurrent_futures (1 min 31 sec)
0:02:01 load avg: 1.88 running: test_concurrent_futures (2 min 1 sec)
0:02:22 load avg: 1.35 [425/425/2] test_concurrent_futures passed (2 min 21 sec)

== Tests result: FAILURE ==

403 tests OK.

2 tests failed:
    test_curses test_unicodedata

20 tests skipped:
    test_devpoll test_gdb test_idle test_ioctl test_kqueue test_msilib
    test_nis test_ossaudiodev test_sqlite test_startfile test_tcl
    test_tix test_tk test_ttk_guionly test_ttk_textonly test_turtle
    test_winconsoleio test_winreg test_winsound test_zipfile64
0:02:22 load avg: 1.35
0:02:22 load avg: 1.35 Re-running failed tests in verbose mode
0:02:22 load avg: 1.35 Re-running test_curses in verbose mode
test_ncurses_version (test.test_curses.MiscTests) ... ncurses_version = curses.ncurses_version(major=6, minor=2, patch=20200212)
ok
test_update_lines_cols (test.test_curses.MiscTests) ... ok
test_alt (test.test_curses.TestAscii) ... ok
test_ascii (test.test_curses.TestAscii) ... ok
test_controlnames (test.test_curses.TestAscii) ... ok
test_ctrl (test.test_curses.TestAscii) ... ok
test_ctypes (test.test_curses.TestAscii) ... ok
test_unctrl (test.test_curses.TestAscii) ... TERM=xterm
ok
test_attributes (test.test_curses.TestCurses) ... ok
test_background (test.test_curses.TestCurses) ... ok
test_beep (test.test_curses.TestCurses) ... ok
test_borders_and_lines (test.test_curses.TestCurses) ... ok
test_chgat (test.test_curses.TestCurses) ... ok
test_clear (test.test_curses.TestCurses) ... ok
test_color_attrs (test.test_curses.TestCurses) ... ok
test_color_content (test.test_curses.TestCurses) ... ok
test_create_windows (test.test_curses.TestCurses) ... ok
test_curs_set (test.test_curses.TestCurses) ... ok
test_enclose (test.test_curses.TestCurses) ... ok
test_encoding (test.test_curses.TestCurses) ... ok
test_endwin (test.test_curses.TestCurses) ... ok
test_env_queries (test.test_curses.TestCurses) ... ok
test_escdelay (test.test_curses.TestCurses) ... ok
test_filter (test.test_curses.TestCurses) ... ok
test_flash (test.test_curses.TestCurses) ... ok
test_getch (test.test_curses.TestCurses) ... ok
test_getmouse (test.test_curses.TestCurses) ... ok
test_getstr (test.test_curses.TestCurses) ... ok
test_getsyx (test.test_curses.TestCurses) ... ok
test_has_colors (test.test_curses.TestCurses) ... ok
test_has_key (test.test_curses.TestCurses) ... ok
test_init_color (test.test_curses.TestCurses) ... skipped 'cannot change color'
test_init_pair (test.test_curses.TestCurses) ... ok
test_input_options (test.test_curses.TestCurses) ... ok
test_insert_delete (test.test_curses.TestCurses) ... ok
test_is_term_resized (test.test_curses.TestCurses) ... ok
test_issue13051 (test.test_curses.TestCurses) ... ok
test_issue21088 (test.test_curses.TestCurses) ... ok
test_issue6243 (test.test_curses.TestCurses) ... ok
test_keyname (test.test_curses.TestCurses) ... ok
test_misc_module_funcs (test.test_curses.TestCurses) ... ok
test_move_cursor (test.test_curses.TestCurses) ... ok
test_new_curses_panel (test.test_curses.TestCurses) ... ok
test_output_character (test.test_curses.TestCurses) ... ok
test_output_options (test.test_curses.TestCurses) ... ok
test_output_string (test.test_curses.TestCurses) ... test_output_string_embedded_null_chars (test.test_curses.TestCurses) ... ok
test_overlay (test.test_curses.TestCurses) ... ok
test_pair_content (test.test_curses.TestCurses) ... ok
test_prog_mode (test.test_curses.TestCurses) ... ok
test_putwin (test.test_curses.TestCurses) ... ok
test_read_from_window (test.test_curses.TestCurses) ... ok
test_refresh (test.test_curses.TestCurses) ... ok
test_refresh_control (test.test_curses.TestCurses) ... ok
test_resize (test.test_curses.TestCurses) ... ok
test_resize_term (test.test_curses.TestCurses) ... ok
test_resizeterm (test.test_curses.TestCurses) ... ok
test_scroll (test.test_curses.TestCurses) ... ok
test_start_color (test.test_curses.TestCurses) ... COLORS = 8
COLOR_PAIRS = 64
ok
test_tabsize (test.test_curses.TestCurses) ... ok
test_terminfo (test.test_curses.TestCurses) ... ok
test_typeahead (test.test_curses.TestCurses) ... ok
test_unctrl (test.test_curses.TestCurses) ... ok
test_unget_wch (test.test_curses.TestCurses) ... ok
test_ungetch (test.test_curses.TestCurses) ... ok
test_use_default_colors (test.test_curses.TestCurses) ... ok
test_use_env (test.test_curses.TestCurses) ... ok
test_userptr_memory_leak (test.test_curses.TestCurses) ... ok
test_userptr_segfault (test.test_curses.TestCurses) ... ok
test_userptr_without_set (test.test_curses.TestCurses) ... test test_curses failed
ok

======================================================================
ERROR: test_output_string (test.test_curses.TestCurses) [window.insstr]
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/sources/Python-3.9.2/Lib/test/test_curses.py", line 284, in test_output_string
    func(s)
_curses.error: inswstr() returned ERR

----------------------------------------------------------------------

Ran 70 tests in 0.285s

FAILED (errors=1, skipped=1)
0:02:22 load avg: 1.35 Re-running test_unicodedata in verbose mode
test_bug_834676 (test.test_unicodedata.NormalizationTest) ... ok
test_edge_cases (test.test_unicodedata.NormalizationTest) ... ok
test_normalization (test.test_unicodedata.NormalizationTest) ... 	fetching http://www.pythontest.net/unicode/13.0.0/NormalizationTest.txt ...
FAIL
test_bidirectional (test.test_unicodedata.UnicodeFunctionsTest) ... ok
test_category (test.test_unicodedata.UnicodeFunctionsTest) ... ok
test_combining (test.test_unicodedata.UnicodeFunctionsTest) ... ok
test_decimal (test.test_unicodedata.UnicodeFunctionsTest) ... ok
test_decomposition (test.test_unicodedata.UnicodeFunctionsTest) ... ok
test_digit (test.test_unicodedata.UnicodeFunctionsTest) ... ok
test_east_asian_width (test.test_unicodedata.UnicodeFunctionsTest) ... ok
test_east_asian_width_9_0_changes (test.test_unicodedata.UnicodeFunctionsTest) ... ok
test_function_checksum (test.test_unicodedata.UnicodeFunctionsTest) ... ok
test_issue10254 (test.test_unicodedata.UnicodeFunctionsTest) ... ok
test_issue29456 (test.test_unicodedata.UnicodeFunctionsTest) ... ok
test_mirrored (test.test_unicodedata.UnicodeFunctionsTest) ... ok
test_numeric (test.test_unicodedata.UnicodeFunctionsTest) ... ok
test_pr29 (test.test_unicodedata.UnicodeFunctionsTest) ... ok
test_method_checksum (test.test_unicodedata.UnicodeMethodsTest) ... ok
test_bug_1704793 (test.test_unicodedata.UnicodeMiscTest) ... ok
test_bug_4971 (test.test_unicodedata.UnicodeMiscTest) ... ok
test_bug_5828 (test.test_unicodedata.UnicodeMiscTest) ... ok
test_decimal_numeric_consistent (test.test_unicodedata.UnicodeMiscTest) ... ok
test_digit_numeric_consistent (test.test_unicodedata.UnicodeMiscTest) ... ok
test_failed_import_during_compiling (test.test_unicodedata.UnicodeMiscTest) ... ok
test_linebreak_7643 (test.test_unicodedata.UnicodeMiscTest) ... ok
test_ucd_510 (test.test_unicodedata.UnicodeMiscTest) ... test test_unicodedata failed
ok

======================================================================
FAIL: test_normalization (test.test_unicodedata.NormalizationTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/sources/Python-3.9.2/Lib/urllib/request.py", line 1346, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
socket.gaierror: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/sources/Python-3.9.2/Lib/test/test_unicodedata.py", line 329, in test_normalization
    testdata = open_urlresource(TESTDATAURL, encoding="utf-8",
urllib.error.URLError: <urlopen error [Errno -3] Temporary failure in name resolution>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/sources/Python-3.9.2/Lib/test/test_unicodedata.py", line 335, in test_normalization
    self.fail(f"Could not retrieve {TESTDATAURL}")
AssertionError: Could not retrieve http://www.pythontest.net/unicode/13.0.0/NormalizationTest.txt

----------------------------------------------------------------------

Ran 26 tests in 8.468s

FAILED (failures=1)
2 tests failed again:
    test_curses test_unicodedata

== Tests result: FAILURE then FAILURE ==

403 tests OK.

2 tests failed:
    test_curses test_unicodedata

20 tests skipped:
    test_devpoll test_gdb test_idle test_ioctl test_kqueue test_msilib
    test_nis test_ossaudiodev test_sqlite test_startfile test_tcl
    test_tix test_tk test_ttk_guionly test_ttk_textonly test_turtle
    test_winconsoleio test_winreg test_winsound test_zipfile64

2 re-run tests:
    test_curses test_unicodedata

Total duration: 2 min 31 sec
Tests result: FAILURE then FAILURE
make[1]: *** [Makefile:1199: test] Error 2
make[1]: Leaving directory '/sources/Python-3.9.2'
